DROP TABLE category IF EXISTS ;
DROP TABLE product IF EXISTS ;
DROP TABLE product_type IF EXISTS ;
DROP TABLE type_desc IF EXISTS ;

CREATE TABLE category(
	id INTEGER NOT NULL,
	name VARCHAR(255),
	PRIMARY KEY (id)
);

CREATE TABLE product(
    id INTEGER NOT NULL,
    name VARCHAR(255),
    price INTEGER,
    quantity INTEGER,
    cat_id INTEGER,
    PRIMARY KEY (id)
);

ALTER TABLE product ADD FOREIGN KEY (cat_id) REFERENCES category(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE TABLE product_type(
	id INTEGER NOT NULL,
	name VARCHAR(255),
	PRIMARY KEY (id)
);

CREATE TABLE type_desc(
	seq INTEGER NOT NULL,
	type_id INTEGER,
	cat_id INTEGER,
	attribute CHAR(1),
	discount INTEGER,
	PRIMARY KEY (seq)
);

ALTER TABLE type_desc ADD FOREIGN KEY (type_id) REFERENCES product_type(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE type_desc ADD FOREIGN KEY (cat_id) REFERENCES category(id) ON UPDATE CASCADE ON DELETE SET NULL;
